import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Baby, BookOpen, CalendarCheck, Check, CheckCircle2, ChevronDown, HeartPulse, MapPin, MessageCircle, Phone, ShieldCheck, Stethoscope, Syringe } from "lucide-react";
import { useState } from "react";
import drAteeq from "@/assets/dr-ateeq.jpg.asset.json";

export const Route = createFileRoute("/")({ component: HomePage });

const phone = "tel:+923142227878";
const whatsapp = "https://wa.me/923142227878";
const maps = "https://maps.app.goo.gl/gZuh8u1VD2PDE2FX9?g_st=aw";

const serviceGroups = [
  { icon: Baby, title: "Neonatal & Newborn Care", intro: "Specialist support for babies from their first examination through early follow-up.", benefit: "Reassurance and a clear plan during the early stages of life.", items: ["Comprehensive newborn examination", "Sick newborn assessment", "Neonatal jaundice assessment and management", "Feeding and breastfeeding problems", "Prematurity follow-up", "Low-birth-weight baby follow-up", "Neonatal infection assessment", "Newborn growth monitoring", "Developmental follow-up", "Counselling for newborn care and warning signs"] },
  { icon: Stethoscope, title: "Pediatric Care", intro: "Assessment and treatment for common childhood illnesses and ongoing concerns.", benefit: "Understand the problem, what needs attention, and what to do next.", items: ["Comprehensive pediatric consultation", "Fever and infections", "Cough, cold and respiratory infections", "Wheezing and asthma", "Pneumonia", "Diarrhea and vomiting", "Constipation", "Abdominal pain and gastrointestinal problems", "Allergic conditions", "Skin problems in children", "Recurrent infections", "Anemia and nutritional deficiencies", "Seizures and febrile seizures", "Pediatric endocrine and metabolic problems", "Chronic and recurrent illnesses"] },
  { icon: HeartPulse, title: "Growth & Development", intro: "Track physical growth and developmental milestones with context and clarity.", benefit: "Identify concerns early and understand when further assessment is needed.", items: ["Weight and height assessment", "BMI assessment", "Growth chart interpretation", "Poor weight gain assessment", "Failure-to-thrive assessment", "Short stature assessment", "Developmental assessment", "Identification of developmental delays", "Guidance on physical and developmental milestones"] },
  { icon: Syringe, title: "Nutrition & Feeding", intro: "Practical counselling for feeding, nutrition and healthy growth at every stage.", benefit: "Replace feeding confusion with practical, individualized guidance.", items: ["Breastfeeding counselling", "Complementary feeding and weaning counselling", "Infant and child nutrition assessment", "Nutritional deficiency assessment and management", "Dietary counselling", "Poor weight gain management", "Underweight and malnutrition management", "Childhood overweight and obesity counselling"] },
  { icon: ShieldCheck, title: "Preventive Child Healthcare", intro: "Support your child's long-term wellbeing, not only the illness of the day.", benefit: "Build healthier routines with monitoring, prevention and parent education.", items: ["Routine child health assessments", "Growth and developmental surveillance", "Nutritional counselling", "Parent education", "Preventive healthcare counselling", "Guidance regarding childhood illnesses and warning signs"] },
  { icon: Stethoscope, title: "In-Clinic Assessment & Support", intro: "Focused clinical assessment and supportive services available at the clinic.", benefit: "Get useful measurements and clinical assessment during the same visit.", items: ["Nebulization", "Growth assessment", "Pulse oximetry", "Developmental assessment", "Comprehensive pediatric clinical examination", "Newborn examination", "Nutritional assessment", "Weight, height and BMI assessment", "Growth chart assessment", "Feeding assessment", "Clinical assessment of respiratory illness", "Parent counselling and health education"] },
];

const concerns = [
  ["Fever & infections", "Persistent fever, recurrent infections and common childhood illnesses."],
  ["Breathing concerns", "Cough, wheezing, asthma and other respiratory symptoms."],
  ["Growth concerns", "Poor weight gain, short stature, BMI and development questions."],
  ["Newborn worries", "Jaundice, feeding, prematurity and newborn warning signs."],
  ["Feeding difficulties", "Breastfeeding, weaning and nutritional concerns."],
  ["Digestive problems", "Vomiting, diarrhea, constipation and abdominal discomfort."],
  ["Allergies & skin", "Allergic conditions and common skin problems in children."],
  ["Development questions", "Milestones, developmental concerns and delays."],
];

const outcomes = [
  ["Clear answers", "Understand what may be happening and what the next step should be."],
  ["Healthy growth", "Keep track of weight, height, nutrition and developmental milestones."],
  ["Appropriate treatment", "Receive evidence-based care with rational use of medicines and investigations."],
  ["Confident parenting", "Get practical counselling for feeding, prevention, warning signs and follow-up."],
];

const resources = [
  ["Child Fever Guide", "What parents should know when a child develops a fever."],
  ["Newborn Care Basics", "Practical guidance for feeding, jaundice and early warning signs."],
  ["Healthy Child Growth", "Understanding growth, nutrition and developmental milestones."],
];

const faqs = [
  ["What does a pediatrician treat?", "Pediatric care covers newborns, infants, children and adolescents, including common childhood illnesses, respiratory symptoms, digestive concerns, allergies, growth concerns and developmental concerns."],
  ["Does Dr. Ateeq provide newborn and neonatal care?", "Yes. Dr. Ateeq Ur Rehman is a Consultant Child Specialist and Neonatologist and provides newborn and neonatal assessment and follow-up."],
  ["Does the clinic provide vaccination services?", "Vaccination services are not currently provided at Arham Childcare Clinic. Parents can still consult Dr. Ateeq about age-appropriate vaccination schedules, catch-up vaccination and vaccine-related counselling."],
  ["Can I consult about poor weight gain or nutrition?", "Yes. Growth, nutrition, weight, height, BMI and feeding assessment are part of the clinic's services."],
  ["Can I bring my child for cough, wheezing or breathing problems?", "Yes. Children can be clinically assessed for respiratory symptoms, wheezing, asthma and other respiratory illnesses."],
  ["How can I book an appointment?", "Call or WhatsApp 03142227878 to schedule your visit."],
  ["Where is Arham Childcare Clinic located?", "The clinic is near Pak Turk School on Multan Public School Road, Model Town, Multan."],
  ["What are the clinic timings?", "Monday to Saturday: 6:00 PM–10:00 PM. Sunday: 10:00 AM–2:00 PM."],
  ["Is emergency care available?", "For emergency-related assistance, call 03357236622. For serious or life-threatening situations, seek immediate emergency medical care rather than waiting for a clinic appointment."],
];

const reviews = [
  {
    name: "Tuba Khan",
    rating: 5,
    date: "2 months ago",
    text: "Dr Ateeq is highly professional, knowledgeable, and compassionate. He listened patiently to all my concerns, explained everything clearly, and provided excellent treatment. The clinic was well-managed, and the staff was courteous. I highly recommend Dr. Ateeq to anyone seeking quality medical care.",
  },
  {
    name: "Rao Hamza",
    rating: 5,
    date: "2 months ago",
    text: "Dr. Ateeq Ur Rehman is an excellent child specialist. He is kind, patient, and listens carefully to parents' concerns. He explains the diagnosis and treatment clearly and provides the best care for children. His professionalism and friendly attitude make every visit comfortable. I highly recommend him to anyone looking for a trustworthy pediatrician.",
  },
  {
    name: "Nadia Ahmad",
    rating: 5,
    date: "2 months ago",
    text: "I had a great experience with Dr.Ateeq, highly professional and compassionate child specialist. What I appreciated most is his calm attitude and the way he gives proper time to each patient without Rushing. His diagnosis is accurate and treatment is effective. It's an honor to learn from and work with such a senior. Highly recommended for paediatric care!!",
  },
  {
    name: "Aqsa Jan",
    rating: 5,
    date: "2 months ago",
    text: "Dr Ateeq is an exceptional paediatrician who treats children with genuine care, kindness and professionalism. He takes the time to explain every aspect of a child's condition clearly to parents, ensuring they feel informed, supported and reassured. His compassion, dedication and expertise make a real difference during challenging times. We are truly grateful for the outstanding care and attention he has provided. Highly recommended.",
  },
];

function HomePage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [expanded, setExpanded] = useState<number | null>(0);

  return (
    <main className="min-h-screen overflow-x-hidden bg-white text-slate-900 pb-20 lg:pb-0">
      <header className="sticky top-0 z-50 border-b border-blue-50 bg-white/95 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
          <a href="#top" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/20"><HeartPulse size={22}/></div><div><div className="text-sm font-extrabold tracking-tight">ARHAM</div><div className="text-[11px] font-semibold tracking-[0.18em] text-blue-600">CHILDCARE CLINIC</div></div></a>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 lg:flex"><a href="#services">Services</a><a href="#doctor">Doctor</a><a href="#facilities">Clinic</a><a href="#resources">Resources</a><a href="#faq">FAQs</a><a href="#contact">Contact</a></nav>
          <a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700"><MessageCircle size={17}/> WhatsApp</a>
        </div>
      </header>

      <section id="top" className="relative overflow-hidden bg-gradient-to-br from-blue-50 via-white to-white">
        <div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 lg:grid-cols-[1.04fr_.96fr] lg:px-8 lg:py-28">
          <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-4 py-2 text-xs font-extrabold uppercase tracking-[0.12em] text-blue-700 shadow-sm"><ShieldCheck size={16}/> Specialist pediatric & neonatal care in Multan</div><h1 className="max-w-3xl text-5xl font-black leading-[1.01] tracking-[-0.05em] sm:text-6xl lg:text-[76px]">Expert care for your child, from <span className="text-blue-600">newborn to adolescence.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 lg:text-xl">Compassionate, evidence-based care focused on accurate diagnosis, healthy growth, nutrition and development—without unnecessary tests or medicines when they are not needed.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={phone} className="inline-flex items-center justify-center gap-2 rounded-full bg-blue-600 px-7 py-4 text-base font-bold text-white shadow-xl shadow-blue-600/20 hover:bg-blue-700"><CalendarCheck size={19}/> Book an Appointment</a><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-slate-200 bg-white px-7 py-4 text-base font-bold text-slate-800 hover:border-blue-200 hover:text-blue-700"><MessageCircle size={19}/> WhatsApp the Clinic</a></div><div className="mt-9 grid max-w-2xl gap-3 sm:grid-cols-3"><TrustCard title="10+ Years" text="Clinical experience"/><TrustCard title="MBBS + FCPS" text="Pediatric Medicine"/><TrustCard title="Specialist" text="Child & neonatal care"/></div></div>
          <div className="relative"><div className="absolute -inset-6 rounded-[46px] bg-blue-100/80 blur-2xl"/><div className="relative rounded-[38px] border border-white bg-white p-3 shadow-2xl shadow-blue-900/10"><div className="relative overflow-hidden rounded-[31px] bg-blue-50"><img src={drAteeq.url} alt="Dr. Ateeq Ur Rehman" className="aspect-[4/5] w-full object-cover object-top"/><div className="absolute inset-x-4 bottom-4 rounded-3xl border border-white/70 bg-white/92 p-5 shadow-xl backdrop-blur-xl"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-blue-600">Dr. Ateeq Ur Rehman</p><p className="mt-1 text-lg font-extrabold text-slate-950">Consultant Child Specialist & Neonatologist</p><p className="mt-2 text-sm leading-6 text-slate-600">Child-friendly care, clear counselling and individualized treatment.</p></div></div></div></div>
        </div>
      </section>

      <section className="border-y border-blue-50 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-blue-50 px-5 py-2 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4 lg:px-8"><Metric number="10+" label="Years of Experience"/><Metric number="FCPS" label="Pediatric Medicine"/><Metric number="Specialist" label="Child & Neonatal Care"/><Metric number="1-on-1" label="Individualized Attention"/></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>WHAT PARENTS REALLY WANT</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Not just treatment. <span className="text-blue-600">Confidence.</span></h2></div><p className="max-w-2xl text-lg leading-8 text-slate-600">When a child is unwell, parents need careful assessment, understandable answers, practical guidance and a clear plan for what happens next.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{outcomes.map(([title,text],i)=><Outcome key={title} index={i+1} title={title} text={text}/>)}</div></section>

      <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow light>THE PROBLEMS WE HELP WITH</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">You want to know what's actually wrong.</h2><p className="mt-5 text-lg leading-8 text-slate-300">From illness and breathing problems to feeding, growth, newborn and developmental concerns, start with a careful specialist assessment.</p></div><div className="grid gap-4 sm:grid-cols-2">{concerns.map(([title,text])=><div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center gap-3"><CheckCircle2 size={18} className="shrink-0 text-blue-300"/><span className="font-extrabold">{title}</span></div><p className="mt-2 pl-7 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></div></div></section>

      <section id="services" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><Eyebrow>DETAILED SERVICES</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">A complete approach to your child's healthcare.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Explore the areas of care available at Arham Childcare Clinic. Open a category to see the detailed services included.</p></div><a href={phone} className="inline-flex w-fit items-center gap-2 rounded-full bg-blue-600 px-6 py-3.5 font-bold text-white hover:bg-blue-700">Talk to the Clinic <ArrowRight size={17}/></a></div><div className="mt-12 space-y-5">{serviceGroups.map((service,index)=>{const Icon=service.icon;const isOpen=expanded===index;return <article key={service.title} className="overflow-hidden rounded-[30px] border border-slate-200 bg-slate-50 shadow-sm"><button type="button" onClick={()=>setExpanded(isOpen?null:index)} className="flex w-full items-start gap-5 p-6 text-left sm:p-8"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-600/15"><Icon size={25}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-4"><h3 className="text-xl font-black tracking-tight sm:text-2xl">{service.title}</h3><ChevronDown size={21} className={`shrink-0 text-blue-600 transition-transform ${isOpen?"rotate-180":""}`}/></div><p className="mt-2 max-w-3xl leading-7 text-slate-600">{service.intro}</p><div className="mt-4 flex items-center gap-2 text-sm font-extrabold text-blue-700"><CheckCircle2 size={16}/> {service.benefit}</div></div></button>{isOpen&&<div className="border-t border-slate-200 bg-white px-6 py-7 sm:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{service.items.map(item=><div key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><Check size={15} className="mt-1 shrink-0 text-blue-600"/><span>{item}</span></div>)}</div></div>}</article>})}</div></div></section>

      <section className="bg-blue-50/70"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><Eyebrow>THE ARHAM CARE APPROACH</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Care that looks beyond the symptom.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Every child is assessed as an individual, with attention to accurate diagnosis, prevention, nutrition, growth and development.</p><a href={phone} className="mt-7 inline-flex items-center gap-2 rounded-full bg-blue-600 px-6 py-3.5 font-bold text-white hover:bg-blue-700">Discuss Your Child's Concern <ArrowRight size={17}/></a></div><div className="grid gap-4 sm:grid-cols-2">{[["Accurate assessment","Start with symptoms, history and clinical findings."],["Evidence-based care","Use appropriate treatment guided by clinical judgement."],["Clear parent counselling","Know what matters, what to watch for and what comes next."],["Child-friendly environment","Keep the clinical experience calm and reassuring."],["Growth & development","Look beyond today's illness to longer-term health."],["Rational treatment","Avoid unnecessary tests and medicines when not needed."]].map(([title,text])=><div key={title} className="rounded-2xl border border-blue-100 bg-white p-6 shadow-sm"><CheckCircle2 className="text-blue-600" size={21}/><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></div></section>

      <section id="doctor" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div className="relative"><div className="absolute -inset-5 rounded-[42px] bg-blue-100 blur-2xl"/><div className="relative overflow-hidden rounded-[36px] border-8 border-white bg-blue-50 shadow-2xl shadow-blue-900/10"><img src={drAteeq.url} alt="Dr. Ateeq Ur Rehman" className="aspect-[4/4.8] w-full object-cover object-top"/></div></div><div><Eyebrow>MEET THE DOCTOR</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Dr. Ateeq Ur Rehman</h2><p className="mt-3 text-lg font-bold text-blue-600">MBBS, FCPS (Pediatrics) · Consultant Child Specialist & Neonatologist</p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Dr. Ateeq Ur Rehman is a Consultant Child Specialist and Neonatologist with experience caring for newborns, infants, children and adolescents. He has worked as a Registrar at Mukhtar A Sheikh Hospital, Multan and Nishtar Hospital, Multan, gaining strong experience in tertiary pediatric and neonatal care.</p><p className="mt-5 max-w-2xl leading-8 text-slate-600">His mission is to provide evidence-based, compassionate child healthcare, focusing on accurate diagnosis, prevention, nutrition, growth and development. His approach emphasizes child-friendly care, parental counselling and avoiding unnecessary tests and medications while ensuring timely, guideline-based treatment.</p><div className="mt-9 grid gap-4 sm:grid-cols-2"><Credential title="MBBS" text="Bachelor of Medicine & Bachelor of Surgery"/><Credential title="FCPS Pediatrics" text="Fellow of College of Physicians & Surgeons Pakistan"/><Credential title="Ex-Registrar" text="Mukhtar A Sheikh Hospital, Multan"/><Credential title="Ex-Registrar" text="Nishtar Hospital, Multan"/></div><div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm font-semibold text-slate-600">PMDC Registration No. <span className="text-slate-950">74532-P</span></div></div></div></div></section>

      <section id="facilities" className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-3xl"><Eyebrow>CLINIC EXPERIENCE</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Comfortable for children. Practical for parents.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A calm, child-friendly environment helps families focus on understanding their child's health and next steps.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{["Comfortable waiting area","Child-friendly consultation environment","Air-conditioned clinic","Parking availability","Wheelchair access","Nebulization facility","Pulse oximetry","Nearby pharmacy facilities"].map(item=><div key={item} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><CheckCircle2 size={19}/></div><p className="mt-4 font-bold">{item}</p></div>)}</div><div className="mt-10 grid gap-5 md:grid-cols-3"><PhotoPlaceholder title="Clinic Exterior"/><PhotoPlaceholder title="Reception & Waiting Area"/><PhotoPlaceholder title="Consultation Room"/></div><p className="mt-4 text-sm text-slate-500">Authentic clinic photographs can replace these placeholders.</p></div></section>

      <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid gap-8 lg:grid-cols-2"><div className="rounded-[30px] border border-blue-100 bg-blue-50 p-8"><div className="flex items-start justify-between gap-4"><div><Eyebrow>VACCINATION GUIDANCE</Eyebrow><h3 className="mt-3 text-3xl font-black tracking-tight">Need help understanding your child's vaccines?</h3></div><Syringe className="text-blue-600" size={30}/></div><p className="mt-5 leading-8 text-slate-600">Vaccination services are not currently provided at the clinic. Parents can still consult Dr. Ateeq regarding age-appropriate vaccination schedules, catch-up vaccination and vaccine-related counselling.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 font-bold text-blue-600">Ask about vaccination guidance <ArrowRight size={17}/></a></div><div className="rounded-[30px] bg-blue-700 p-8 text-white"><Eyebrow light>HOW IT WORKS</Eyebrow><h3 className="mt-3 text-3xl font-black tracking-tight">Three simple steps to get started.</h3><div className="mt-7 space-y-6"><Step number="01" title="Book your visit" text="Call or WhatsApp 03142227878."/><Step number="02" title="Get a comprehensive assessment" text="Your child's symptoms, history, growth and overall health are carefully reviewed."/><Step number="03" title="Leave with a clear plan" text="Receive appropriate treatment, counselling and follow-up recommendations."/></div></div></div></div></section>

      <section id="resources" className="bg-blue-50/60"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><Eyebrow>PARENT RESOURCES & BLOG</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Helpful answers for everyday child-health questions.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Build a useful resource library that supports parents between visits.</p></div><a href="#contact" className="inline-flex w-fit items-center gap-2 font-bold text-blue-700">View all resources <ArrowRight size={17}/></a></div><div className="mt-12 grid gap-5 md:grid-cols-3">{resources.map(([title,text],i)=><article key={title} className="rounded-[26px] border border-blue-100 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><BookOpen size={23}/></div><p className="mt-6 text-xs font-extrabold uppercase tracking-[0.12em] text-blue-600">Article 0{i+1}</p><h3 className="mt-2 text-xl font-extrabold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><a href="#contact" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-600">Read article <ArrowRight size={15}/></a></article>)}</div></div></section>

      <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="text-center"><Eyebrow>PARENT TESTIMONIALS</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Trusted by parents across Multan.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Real Google reviews from parents and patients who have shared their experience with Dr. Ateeq.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{reviews.map((review)=><article key={review.name} className="group rounded-[26px] border border-slate-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/5"><div className="flex items-start justify-between gap-4"><div><div className="flex gap-1 text-amber-500" aria-label={`${review.rating} out of 5 stars`}>{Array.from({length: review.rating}).map((_,i)=><span key={i}>★</span>)}</div><p className="mt-4 text-xs font-extrabold uppercase tracking-[0.12em] text-blue-600">Google Review</p></div><div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-50 text-sm font-black text-blue-700">{review.name.charAt(0)}</div></div><p className="mt-5 text-[15px] leading-7 text-slate-600">“{review.text}”</p><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><div><p className="font-extrabold text-slate-900">{review.name}</p><p className="mt-1 text-xs text-slate-400">{review.date}</p></div><div className="text-xs font-bold text-slate-400">Verified on Google</div></div></article>)}</div><div className="mt-10 text-center"><a href={maps} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-6 py-3.5 text-sm font-extrabold text-slate-800 shadow-sm transition hover:border-blue-200 hover:text-blue-700">See all Google Reviews <ArrowRight size={17}/></a></div></div></section>

      <section id="faq" className="bg-slate-50"><div className="mx-auto max-w-4xl px-5 py-20 lg:py-28"><div className="text-center"><Eyebrow>FAQS</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Questions parents often ask.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Answers to the questions that commonly come before booking.</p></div><div className="mt-12 overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm">{faqs.map(([q,a],i)=><button key={q} type="button" onClick={()=>setOpenFaq(openFaq===i?null:i)} className="block w-full border-b border-slate-100 p-6 text-left last:border-b-0"><div className="flex items-center justify-between gap-6"><span className="text-base font-extrabold sm:text-lg">{q}</span><ChevronDown size={20} className={`shrink-0 text-blue-600 transition-transform ${openFaq===i?"rotate-180":""}`}/></div>{openFaq===i&&<p className="mt-4 pr-8 text-sm leading-7 text-slate-600 sm:text-base">{a}</p>}</button>)}</div></div></section>

      <section id="contact" className="bg-blue-700 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div><Eyebrow light>FINAL STEP</Eyebrow><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Give your child the specialist care they deserve.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100">Whether you are concerned about an illness, newborn health, feeding, growth or development, start with a careful specialist assessment.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={phone} className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 font-bold text-blue-700"><Phone size={18}/> Call 03142227878</a><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 bg-white/10 px-7 py-4 font-bold text-white"><MessageCircle size={18}/> WhatsApp the Clinic</a></div></div><div className="rounded-[30px] border border-white/15 bg-white/10 p-7 backdrop-blur"><div className="flex items-center gap-3"><MapPin size={22}/><h3 className="text-xl font-extrabold">Visit Arham Childcare Clinic</h3></div><p className="mt-4 leading-7 text-blue-100">Near Pak Turk School,<br/>Multan Public School Road,<br/>Model Town, Multan</p><div className="mt-7 border-t border-white/15 pt-6"><p className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Clinic Hours</p><p className="mt-2 leading-7">Monday–Saturday: <strong>6 PM–10 PM</strong><br/>Sunday: <strong>10 AM–2 PM</strong></p></div><div className="mt-5 border-t border-white/15 pt-5"><p className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Emergency Contact</p><p className="mt-2 font-extrabold">03357236622</p></div><a href={maps} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 font-bold">Get Directions <ArrowRight size={17}/></a></div></div></section>

      <footer className="bg-slate-950 text-slate-300"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-[1.2fr_.8fr_.9fr_.9fr]"><div><div className="text-sm font-extrabold text-white">ARHAM</div><div className="mt-1 text-[11px] font-semibold tracking-[0.18em] text-blue-400">CHILDCARE CLINIC</div><p className="mt-5 max-w-sm text-sm leading-7 text-slate-400">Specialist pediatric and neonatal care in Multan with a focus on accurate assessment, healthy growth and clear guidance for parents.</p></div><div><p className="font-bold text-white">Explore</p><div className="mt-4 grid gap-2 text-sm"><a href="#services">Services</a><a href="#doctor">Doctor</a><a href="#facilities">Clinic Experience</a><a href="#resources">Parent Resources</a><a href="#faq">FAQs</a></div></div><div><p className="font-bold text-white">Contact</p><div className="mt-4 grid gap-2 text-sm"><a href={phone}>03142227878</a><a href={whatsapp}>WhatsApp</a><a href="mailto:nishtarian20@yahoo.com" className="break-all">nishtarian20@yahoo.com</a><span>Emergency: 03357236622</span></div></div><div><p className="font-bold text-white">Location</p><p className="mt-4 text-sm leading-7 text-slate-400">Near Pak Turk School<br/>Multan Public School Road<br/>Model Town, Multan</p><a href={maps} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-blue-400">Get Directions <ArrowRight size={15}/></a></div></div><div className="mt-10 border-t border-white/10 pt-6 text-xs leading-6 text-slate-500">© {new Date().getFullYear()} Arham Childcare Clinic. All rights reserved. Medical information on this website is for general education and does not replace professional medical assessment.</div></div></footer>

      <div className="fixed inset-x-3 bottom-3 z-50 grid grid-cols-3 gap-2 rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-2xl backdrop-blur lg:hidden"><a href={phone} className="flex items-center justify-center gap-1.5 rounded-xl bg-blue-600 py-3 text-xs font-extrabold text-white"><Phone size={16}/> Call</a><a href={whatsapp} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-1.5 rounded-xl bg-slate-900 py-3 text-xs font-extrabold text-white"><MessageCircle size={16}/> WhatsApp</a><a href="#contact" className="flex items-center justify-center gap-1.5 rounded-xl bg-blue-50 py-3 text-xs font-extrabold text-blue-700"><CalendarCheck size={16}/> Book</a></div>
    </main>
  );
}

function Eyebrow({ children, light = false }: { children: string; light?: boolean }) { return <div className={`text-xs font-extrabold uppercase tracking-[0.16em] ${light ? "text-blue-200" : "text-blue-600"}`}>{children}</div>; }
function Metric({ number, label }: { number: string; label: string }) { return <div className="px-5 py-5 text-center sm:py-6"><div className="text-2xl font-black text-blue-600">{number}</div><div className="mt-1 text-xs font-semibold text-slate-500 sm:text-sm">{label}</div></div>; }
function TrustCard({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-blue-100 bg-white/90 p-4 shadow-sm"><p className="font-extrabold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>; }
function Outcome({ index, title, text }: { index: number; title: string; text: string }) { return <article className="rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/5"><div className="text-sm font-black text-blue-600">0{index}</div><h3 className="mt-8 text-xl font-extrabold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>; }
function Credential({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="font-extrabold">{title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="flex gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/15 text-xs font-black">{number}</div><div><p className="font-extrabold">{title}</p><p className="mt-1 text-sm leading-6 text-blue-100">{text}</p></div></div>; }
function PhotoPlaceholder({ title }: { title: string }) { return <div className="flex aspect-[16/10] items-center justify-center rounded-[26px] border border-dashed border-blue-200 bg-white text-center"><div><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Stethoscope size={22}/></div><p className="mt-4 font-extrabold text-slate-700">{title}</p><p className="mt-1 text-sm text-slate-400">Authentic clinic photo placeholder</p></div></div>; }
